model:
  base_learning_rate: 4.5e-06
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    # ckpt_path: logs/2021-08-17T07-36-02_sun360_basic_transformer/checkpoints/last.ckpt # set for resume
    cond_stage_key: concat_input
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 1024
        block_size: 512 # When input image is 256x256, set as 512. When input is 256x512(VQ: 16x32), set as 1024.
        n_layer: 16
        n_head: 16
        n_embd: 256
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: /share/zhlu6105/checkpoints/vqgan2.ckpt # Set your trained VQGNA_2 model
        embed_dim: 256
        n_embed: 1024
        image_key: image
        concat_input: False 
        completion: False
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss 
    cond_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: /share/zhlu6105/checkpoints/vqgan1.ckpt # Set your trained VQGAN_1 model
        embed_dim: 256
        n_embed: 1024
        image_key: concat_input
        concat_input: True # important
        completion: False
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 7
          out_ch: 7
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss 
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 24
    num_workers: 12
    train:
      target: taming.data.sun_comp.Sun360CompBase
      params:
          data_csv:  ./train_sort.txt
          data_root: /share/zhlu6105/dataset/video_frames/train
          size: 256
          random_crop: True
          coord: True
          interpolation: area
          no_crop: True
          no_rescale: False
    validation:
      target: taming.data.sun_comp.Sun360CompBase
      params:
          data_csv: ./test_sort.txt
          data_root: /share/zhlu6105/dataset/video_frames/test
          size: 256
          random_crop: True
          coord: True
          interpolation: area
          no_crop: True
          no_rescale: False
    test:
      target: taming.data.sun_comp.Sun360CompBase
      params:
        data_csv: ./test_sort.txt
        data_root: /share/zhlu6105/dataset/video_frames/test
        size: 256
        random_crop: False 
        coord: True
        interpolation: area
        no_crop: True
        no_rescale: False 

